#!/usr/bin/env bash
# Bash script that creates the file /var/run/holbertonscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

sigterm_handler() {
	echo "I hate the kill command"
}

sigint_handler() {
	echo "Y U no love me?!"
}

sigquit_handler() {
	echo "Deleting PID file and terminating script"
	rm -f /var/run/myscript.pid
	exit
}

echo $$ > /var/run/myscript.pid

trap 'sigterm_handler' SIGTERM
trap 'sigint_handler' SIGINT
trap 'sigquit_handler' SIGQUIT SIGTERM

while true; do
	echo "To infinity and beyond"
	sleep 1
done
