#!/usr/bin/env bash
# Bash script that displays all active IPv4 IPs on the machine it’s executed on.

interfaces=$(ip addr show | awk '/inet / {print $NF}')
for interface in $interfaces; do
	ipv4=$(ip addr show "$interface" | awk '/inet / {print $2}')
	echo "$ipv4"
done
